# .github/dependabot.yml - Автоматические обновления зависимостей
version: 2
updates:
  # NPM зависимости
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    reviewers:
      - "deep-team"
    assignees:
      - "deep-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    
    # Группировка обновлений
    groups:
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright*"
      testing:
        patterns:
          - "*jest*"
          - "*test*"
          - "ajv*"
      build:
        patterns:
          - "*webpack*"
          - "*babel*"
          - "*rollup*"
      linting:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*lint*"
    
    # Игнорируем major обновления для критических зависимостей
    ignore:
      - dependency-name: "cheerio"
        update-types: ["version-update:semver-major"]
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "undici"
        update-types: ["version-update:semver-major"]
        
    # Разрешаем автомерж для patch и minor обновлений
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
        
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 2
    reviewers:
      - "deep-team"
    labels:
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"