site_name: Deep Components Aggregator
site_description: Electronic components search and aggregation platform
site_url: https://deep-agg.github.io/docs/
repo_url: https://github.com/deep-agg/deep-agg
repo_name: deep-agg/deep-agg

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - Search Flow: architecture/search-flow.md
    - Data Flow: architecture/data-flow.md
  - Providers:
    - Overview: providers/overview.md
    - Digi-Key: providers/digikey.md
    - Mouser: providers/mouser.md
    - Farnell: providers/farnell.md
    - TME: providers/tme.md
  - Operations:
    - Currency: operations/currency.md
    - Metrics: operations/metrics.md
    - Health Checks: operations/health.md
